name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - testing
  pull_request:
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: ci
    uses: craftcms/.github/.github/workflows/ci.yml@feature/params
    with:
      craft_version: '4'
      jobs: ${{ toJson(["ecs", "phpstan"]) }}